apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: scenario-01
  labels:
    service: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
        service: cart-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8101"
    spec:
      containers:
      - name: cart-service
        image: docker.io/causely-oss/cart-service:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8101
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4318
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        - name: OTEL_SERVICE_NAME
          value: cart-service
        - name: CATALOG_SERVICE_URL
          value: http://catalog-service:8102
        - name: PRICING_SERVICE_URL
          value: http://pricing-service:8097
        - name: SESSION_SERVICE_URL
          value: http://session-service:8106
        - name: REDIS_URL
          value: redis://redis:6379/5
        readinessProbe:
          httpGet:
            path: /health
            port: 8101
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
